package entity

import (
	"time"

	"fms-project/internal/domain/valueobject"
)

// CategoryStat represents aggregated statistics for a categor
type CategoryStat struct {
	CategoryID    valueobject.UUID
	CategoryName  string
	CategoryIcon  string
	Total         valueobject.MoneyAmount
	Percentage    float64 // 0-100
	PurchaseCount int     // Number of purchases in this category
}

// PurchaseStat represents aggregated statistics for a purchase
type PurchaseStat struct {
	PurchaseID       valueobject.UUID
	PurchaseDate     time.Time
	OrganisationName string
	Total            valueobject.MoneyAmount
	ItemCount        int // Number of expense items in purchase
}

// Comparison represents comparison between current and previous period
type Comparison struct {
	CurrentPeriod  valueobject.Period
	PreviousPeriod valueobject.Period
	CurrentTotal   valueobject.MoneyAmount
	PreviousTotal  valueobject.MoneyAmount
	DeltaPercent   float64 // Positive for growth, negative for decline
}

// CategoryDelta represents change in spending for a specific categor
type CategoryDelta struct {
	CategoryID    valueobject.UUID
	CategoryName  string
	CurrentTotal  valueobject.MoneyAmount
	PreviousTotal valueobject.MoneyAmount
	DeltaPercent  float64 // Positive for growth, negative for decline
}

// Anomaly represents an unusually expensive purchase
type Anomaly struct {
	PurchaseID   valueobject.UUID
	PurchaseDate time.Time
	Name         string // Organisation name or purchase description
	Total        valueobject.MoneyAmount
	AvgCategory  valueobject.MoneyAmount // Category average used for comparison
	Factor       float64                 // How many times above average
}

type InsightType string

const (
	InsightTypeTrend   InsightType = "trend"
	InsightTypeAnomaly InsightType = "anomaly"
	InsightTypePattern InsightType = "pattern"
	InsightTypeChange  InsightType = "change"
)

// Insight represents a text insight generated by AI
type Insight struct {
	Text string
	Type InsightType
}

// Summary represents Level 1 quick analytics view
// Contains essential data for first display
type Summary struct {
	Period        valueobject.Period
	Total         valueobject.MoneyAmount
	PurchaseCount int
	ExpenseCount  int
	TopCategories []CategoryStat // Top categories by total
	TopPurchases  []PurchaseStat // Top most expensive purchases
}

// DetailedReport represents Level 2 extended analytics view
// Contains full analysis with comparisons, deltas, anomalies and AI insights
type DetailedReport struct {
	Summary        Summary
	Comparison     Comparison
	CategoryDeltas []CategoryDelta // Categories with significant changes
	Anomalies      []Anomaly       // Unusually expensive purchases
	Insights       []Insight       // AI-generated insights
}
